"""Add tag column to document table

Revision ID: 8bb6ee6f8eec
Revises: 7c3dd987446a
Create Date: 2025-06-13 16:56:24.701738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb6ee6f8eec'
down_revision: Union[str, None] = '7c3dd987446a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'tags')
    # ### end Alembic commands ###
