"""Add description column to document table

Revision ID: d985138e2cb8
Revises: 8bb6ee6f8eec
Create Date: 2025-06-13 17:03:32.067391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd985138e2cb8'
down_revision: Union[str, None] = '8bb6ee6f8eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'description')
    # ### end Alembic commands ###
